version: "3.9"
services:
  flask_compose:
    image: apiflask:1
    ports:
      - "5000:5000"
    links:
      - databaseserver
  databaseserver:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=itl
